spring:
  application:
    name: greeting
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:6033/encore
    username: todo_user
    password: todo_passwd
server:
  port: 8080
mybatis:
  mapper-locations: mappers/*.xml